# Generated by Django 5.2.6 on 2025-09-05 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_rename_created_at_question_asked_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answered_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='asked_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qna.question'),
        ),
    ]
